services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_pi
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    restart: always

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: pi
      MYSQL_USER: pi.dev
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin_container
      restart: always
      ports:
        - "8080:80" 
      environment:
        PMA_HOST: db 
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_PASSWORD: 123
        PMA_ARBITRARY: 1 
      depends_on:
        - db

volumes:
  mysql_data:
    driver: local